name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NPM
      uses: actions/setup-node@v1
      with:
        version: 14
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

    # - name: Publish code coverage reports to codecove.io
      # uses: codecov/codecov-action@v1
      # with:
      #   token: ${{ secrets.CODECOV_TOKEN }}
      #   files: ./**/coverage.cobertura.xml
      #   fail_ci_if_error: true

    
